### ISSUE TITLE
CFP Randomization causing some EI to not wear clothes for some players

### ISSUE THREAD

**Issue by Grewsome2018** [Task-Force-Raider/HeartsAndMindsTFR#25]
As title suggests

**Comment by McFurSun** [comment]
They were just called to stand to and didn't have time to get dressed.... :smile: 

On a serious note, 3CB had a module that you placed to disable randomisation.
Unsure if CFP has it to, although it does have it in the init for each unit if you were to place them individually in editor, which isn't helpful with dynamically spawning AI.

It is also strange that only certain people could not see there clothes. Could it be to do with mod conflict due to them running unapproved mods as we don't have key checks......

**Comment by the-pope-himself** [comment]
I haven't encountered this issue but will investigate tomorrow once the latest version is up and see if I can replicate.

**Comment by Grewsome2018** [comment]
I think only McFur and Saylon had it on the first play test

**Comment by McFurSun** [comment]
Will have to try and replicate this using the latest release.
If it occurs again, will have to see if relog ing or restarting arma fixes it.

**Comment by Grewsome2018** [comment]
This'll sound real weird but I noticed this was an issue for me on Liv Lib the other night lol - i'm running standard mod list and Anizay as the only additional mod...

**Comment by BroBeansCPG** [comment]
- Didn’t notice it in todays play test which is good

**Comment by Grewsome2018** [comment]
Unable to replicate in 0.8b 0.85b and 0.9b

**Comment by McFurSun** [comment]
Seen it again last night. Only with units in  vehicle.

When I first saw it on the initial test, they were all riding on the back of a BTR/BMP.
I did see them on foot after that so I'm thinking they were dismounts.

**Comment by the-pope-himself** [comment]
Saw last night as well. Again, crew members like McFur, but in a technical.

**Comment by McFurSun** [comment]
Yeah mine was a techie to last night. Just outside the power plant you guys were sniping from.

I think it's just something were going to have to deal with

**Comment by Grewsome2018** [comment]
Unable to resolve - seems to be more of an issue when mission has been ongoing for quite some time.
